### ISSUE TITLE
Python 3 on Appveyor is failing

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/privacypass#18]
```
Traceback (most recent call last):
  File "C:\spike.py", line 231, in <module>
    main(*argv[1:])
  File "C:\spike.py", line 209, in main
    message = b"allocate_buckets {storage_index}".format(storage_index=b"ABCDEFGH")
AttributeError: 'bytes' object has no attribute 'format'
```

**Comment by exarkun** [comment]
Broken since Python 3 Windows CI was added, looks like.  I think this is the first master revision with this appveyor config - https://ci.appveyor.com/project/exarkun/privacypass/builds/29952255/job/625qqscpb2fowu60 - and it fails the same way.
